# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Chocofi nice_nano_v2 nice_view'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_view_adapter nice_view_gem","corne_right nice_view_adapter nice_view_gem","settings_reset"]'
      alphas: '["QWERTY"]'
      custom_config: '["#define MIRYOKU_KLUDGE_SOFT_OFF"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_POINTING=y\nCONFIG_ZMK_PM_SOFT_OFF=y\nCONFIG_ZMK_KEYBOARD_NAME=\"Chocofi\""]'
      branches: '["zmkfirmware/zmk/v0.3-branch"]'
      modules: '["M165437/nice-view-gem/v0.3.0"]'
